// =============================================================================
//
// Barcode VCL Component
//
// For Delphi 4/5/6/7, C++ Builder 4/5/6, BDS 2005/2005, Turbo Delphi 2006
//
// Copyright (c) 2001, 2007  Han-soft Software, all rights reserved.
//
// $Rev: 44 $   $Id: Barcode_ful.inc 44 2007-01-16 01:16:04Z hanjy $
//
// =============================================================================

{$DEFINE ENGLISH}

{$IFDEF ENGLISH}
const
  ErrorBarcode  = 'Barcode must be numeric.';
  ErrorBarType  = 'Wrong barcode type.';
  ErrorLength   = 'Invalid barcode length.';
  ErrorCode93   = 'Code_93 bad data.';
  ErrorInternal = 'Internal Error.';
  CopyrightInfo = 'BarCode VCL Component, Copyright(C) Han-soft Software.' +
                  '(http://www.han-soft.com)';
{$ENDIF}

