/**
 * <b>项目名：</b>NvBusEJB<br/>
 * <b>包名：</b>cn.nova.bus.report.dao<br/>
 * <b>文件名：</b>DepartinvoicesDayReportDao.java<br/>
 * <b>版本信息：</b>v4.0<br/>
 * <b>日期：</b>2012-8-31 上午11:43:46<br/>
 * <b>Copyright (c)</b> 2011深圳市南凌科技发展有限公司-版权所有<br/>
 */
package cn.nova.bus.report.dao;

import java.util.Date;
import java.util.List;

import javax.persistence.Query;

import cn.nova.bus.dao.EntityManagerDaoSurport;
import cn.nova.utils.orm.PropertyFilter;

/**
 * <b>类描述：</b><br/>
 * <b>类名称：</b>DepartinvoicesDayReportDao.java<br/>
 * <b>创建人：</b><a href="mailto:lijinhui@nova.net.cn">李金辉</a><br/>
 * <b>创建时间：</b>2012-8-31 上午11:43:46<br/>
 * <b>关键修改：</b><br/>
 * <b>修改时间：</b><br/>
 * <b>修改人：</b><br/>
 */
@SuppressWarnings("rawtypes")
public class DepartinvoicesDayReportDao extends EntityManagerDaoSurport {

	/**
	 * 发往各省、地客运量日统计表
	 * 
	 * @param startdate
	 * @param enddate
	 * @param orgid 班次机构
	 * @param isbytime 是否按发车时间统计
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public List<Object> queryDepDayReport(Date startdate, Date enddate,
			String orgid,boolean isbytime) {
		StringBuffer sql = new StringBuffer();
		if (!isbytime){		
			sql.append("select decode(grouping(a.name), 1, '', a.name) name, ");
			sql.append(
				" decode(grouping(a.stationname)+grouping(a.name),1, '小计',2,'合计', a.stationname) stationname,'' as starttime, ")
				.append(" sum(a.vnum) vehiclenum, ")
				.append(" sum(b.schedulenum- (case when c.overschedulenum is null then 0 else c.overschedulenum end )) schedulenum,")//所有班次减去加班班次等于正班班次（为0 没有正班）
				.append(" sum(b.ticketnum-(case when c.overticketnum is null then 0 else c.overticketnum end )) ticketnum,")
				.append(" decode(sum(c.overschedulenum),null,0,sum(c.overschedulenum)) overschedulenum, ")
				.append(" sum(b.schedulenum) as allschedulenum,")
				.append(" decode(sum(c.overticketnum),null,0,sum(c.overticketnum)) overticketnum")
				 .append(",sum(dd.totalamount) moneypayable ")
				.append(" ,sum(dd.peopledistance) peopledistance,sum(dd.rate) || '%' rate,sum(dd.needpeopledistance) needpeopledistance  ")
				.append(" from ")
				.append(" (select a.name, a.stationname, count(a.vehicleid) vnum from (select dt.name,st.name stationname,d.vehicleid from ")
				.append(" departinvoices d,schedule s,route r,station st,district dt where d.scheduleid=s.id ")
				.append(" and s.routeid=r.id and r.endstationid=st.id and d.status!=1 and st.districtid=dt.id ")
				.append(" and d.departdate between :startdate and :enddate and s.orgid in ")
				.append(orgid)
				.append(" group by dt.name,st.name,d.vehicleid) a group by a.name, a.stationname order by a.name) a, ")
				.append(" (select b.name,b.stationname, count(b.reportid) schedulenum,sum(b.ticketnum) ticketnum from ")
				.append(" (select dt.name,st.name stationname,d.reportid,sum(d.ticketnum) ticketnum from departinvoices d,schedule s, ")
				.append(" route r,station st, scheduleplan sp,district dt ")
				.append(" where d.scheduleid=s.id and s.routeid=r.id and r.endstationid=st.id and d.status!=1 ")
				.append(" and d.scheduleplanid=sp.id  and st.districtid=dt.id ")//and sp.isovertime=0
				.append(" and d.departdate between :startdate and :enddate and s.orgid in ")
				.append(orgid)
				.append(" group by dt.name,st.name,d.reportid) b group by b.name,b.stationname order by b.name) b, ")//统计所有发班的运量情况
				.append(" (select c.name,c.stationname, count(c.reportid) overschedulenum,sum(c.ticketnum) overticketnum from ")
				.append(" (select dt.name,st.name stationname,d.reportid,sum(d.ticketnum) ticketnum from departinvoices d,schedule s, ")
				.append(" route r, station st, scheduleplan sp,district dt ")
				.append(" where d.scheduleid=s.id and s.routeid=r.id and r.endstationid=st.id and d.status!=1 ")
				.append(" and d.scheduleplanid=sp.id and sp.isovertime=1 and st.districtid=dt.id ")
				.append(" and d.departdate between :startdate and :enddate and s.orgid in ")
				.append(orgid)
				.append(" group by dt.name,st.name,d.reportid) c group by c.name,c.stationname order by c.name) c ")//统计加班运量情况
				// 周转量、实载率，营收拷贝发班运量统计表
				.append("  ,( ")
				.append("  select ")
				.append("  name,stationname, ")
				.append("  nvl(sum(totalamount), 0) totalamount, ")
				.append("  nvl(sum(basemount), 0) basemount, ")
				.append("  nvl(sum(income), 0) as moneypayable, ")
				.append("  nvl(sum(balanceamount), 0) balanceamount, ")
				.append("  nvl(sum(peopledistance), 0) peopledistance, ")
				.append("  nvl(sum(needpeopledistance), 0) needpeopledistance, ")
				.append("  nvl(sum(rate),0 ) rate  ")
				.append("  ")
				.append("  from ( ")
				.append("  select ")
				.append("  bs.name,bs.stationname, ")
				.append("  bs.scorgname, ")
				.append("  bs.rname, ")
				.append("  sum(bs.needpeopledistance) needpeopledistance, sum(nl.totalamount) totalamount, ")
				.append("  sum(nl.basemount) basemount, sum(nl.income) income, sum(nl.balanceamount) balanceamount, sum(nl.peopledistance) peopledistance ")
				.append("  ,sum(nvl((case bs.needpeopledistance when 0 then '0' ")
				.append("  else	(to_char(nl.peopledistance * 100 / bs.needpeopledistance, 	'990.99')) end),0 )) as rate ")
				.append("  from ( ")
				.append("  select ")
				.append("  dt.name,st.name stationname, ")
				.append("  sco.name scorgname,r.name rname,r.id routeid, ")
				.append("  v.vehicleno, ")
				.append("  sum(v.seatnum * r.distance) needpeopledistance ")
				.append("  from schedulestatus ss,scheduleplan sp,vehiclereport ")
				.append("  vp,vehicle v,schedule sc, ")
				.append("  route r,organization sco,Station st,district dt where ")
				.append("  st.id=r.endstationid ")
				.append("  and st.districtid=dt.id ")
				.append("  and ss.scheduleplanid = sp.id and ss.scheduleid = sc.id and ")
				.append("  sc.routeid = r.id ")
				.append("  and sc.islinework = 1 and sc.districttype in (0,1,2,3,4) and ")
				.append("  sp.id = vp.scheduleplanid and vp.isactive = 1 ")
				.append("  and ss.departstationid=sco.stationid and vp.vehicleid = v.id ")
				.append("  and sc.orgid = sco.id ")
				.append("  and ss.departdate=sp.departdate and sp.departdate between ")
				.append("  :startdate and ")
				.append("  :enddate and sco.id in ")
				.append(orgid)
				.append(" ")
				.append("  group by sco.name, r.name,r.id, v.vehicleno,dt.name,st.name ")
				.append("  ) bs ")
				.append("  left join ( ")
				.append("  select ")
				.append("  st.name,dt.name stationname, ")
				.append("  sco.name scorgname,r.name rname,r.id routeid, ")
				.append("  v.vehicleno, ")
				.append("  sum(dv.totalamount) as totalamount, ")
				.append("  sum(dv.totalamount - dv.stationservicefee -dv.fueladditionfee ")
				.append("  - dv.othterfee) as basemount, ")
				.append("  sum(dv.balanceamount) balanceamount,sum(de.peopledistance) ")
				.append("  peopledistance, ")
				.append("  sum(dv.stationservicefee + dv.othterfee + dv.agentfee) income ")
				.append("  from departinvoices dv,route r,schedule s,( ")
				.append("  select dt.departinvoicesid,sum(dt.distance * dt.ticketnum) ")
				.append("  peopledistance ")
				.append("  from departinvoicesdetail dt where dt.departdate between ")
				.append("  :startdate and ")
				.append("  :enddate ")
				.append("  group by dt.departinvoicesid ")
				.append("  ) de,vehicle v,organization sco,Station st,district dt where ")
				.append("  st.id=r.endstationid ")
				.append("  and st.districtid=dt.id ")
				.append("  and dv.scheduleid = s.id ")
				.append("  and s.orgid = sco.id ")
				.append("  and s.islinework = 1 and s.routeid = r.id and s.districttype ")
				.append("  in (0,1,2,3,4) and dv.id = de.departinvoicesid(+) ")
				.append("  and dv.departdate between :startdate ")
				.append("  and :enddate and sco.id in ")
				.append(orgid)
				.append(" ")
				.append("  and dv.status <> '1' and dv.vehicleid = v.id ")
				.append("  group by sco.name, r.name,r.id,v.vehicleno,dt.name,st.name ")
				.append("  ) nl on bs.scorgname = nl.scorgname ")
				.append("  and bs.rname = nl.rname and bs.routeid = nl.routeid and ")
				.append("  bs.vehicleno = nl.vehicleno ")
				.append("  group by bs.rname,bs.name,bs.stationname,bs.scorgname ")
				.append("  union all ")
				.append("  ")
				.append("  select ")
				.append("  bs.name,bs.stationname, ")
				.append("  bs.scorgname, bs.rname, ")
				.append("  sum(bs.needpeopledistance) needpeopledistance, sum(nl.totalamount) totalamount, ")
				.append("  sum(nl.basemount) basemount, sum(nl.income) income, sum(nl.balanceamount) balanceamount, sum(nl.peopledistance) peopledistance ")
				.append("  ,sum(nvl((case bs.needpeopledistance when 0 then '0' ")
				.append("  else	(to_char(nl.peopledistance * 100 / bs.needpeopledistance, 	'990.99')) end),0 )) as rate ")
				.append("  from ( ")
				.append("  ")
				.append("  select dt.name,st.name stationname,sco.name scorgname, r.name ")
				.append("  rname,r.id routeid, ")
				.append("  sum((sp.seatnum - sp.fixedreserveseatnum) * r.distance) ")
				.append("  needpeopledistance ")
				.append("  from schedulestatus ss, scheduleplan sp, schedule sc, route ")
				.append("  r, organization sco, ")
				.append("  vehiclereport rp,vehicle v,Station st,district dt where ")
				.append("  st.id=r.endstationid ")
				.append("  and st.districtid=dt.id ")
				.append("  and ss.scheduleplanid = sp.id ")
				.append("  and ss.scheduleid = sc.id ")
				.append("  and sc.routeid = r.id and sc.islinework = 0 and sc.orgid = ")
				.append("  sco.id and sc.districttype in (0,1,2,3,4) ")
				.append("  and ss.departdate = sp.departdate and sp.departdate between ")
				.append("  :startdate and ")
				.append("  :enddate ")
				.append("  and sco.id in ")
				.append(orgid)
				.append(" and rp.scheduleplanid=sp.id and ")
				.append("  sc.id=rp.scheduleid and rp.vehicleid=v.id ")
				.append("  and rp.isactive=1 group by sco.name, ")
				.append("  r.name,r.id,dt.name,st.name ")
				.append("  ) bs ")
				.append("  left join ( ")
				.append("  select ")
				.append("  dt.name,st.name stationname, ")
				.append("  sco.name scorgname,r.name rname,r.id ")
				.append("  routeid,v.vehicleno, ")
				.append("  sum(dv.totalamount - dv.stationservicefee - ")
				.append("  dv.fueladditionfee - dv.othterfee) as basemount, ")
				.append("  sum(dv.balanceamount) balanceamount,sum(de.peopledistance) ")
				.append("  peopledistance, ")
				.append("  sum(dv.totalamount) as totalamount, sum(dv.stationservicefee ")
				.append("  + dv.othterfee + dv.agentfee) income ")
				.append("  from departinvoices dv, route r, schedule s, scheduleplan sp, ")
				.append("  ( ")
				.append("  select dt.departinvoicesid, sum(dt.distance * dt.ticketnum) ")
				.append("  peopledistance ")
				.append("  from departinvoicesdetail dt where dt.departdate between ")
				.append("  :startdate and ")
				.append("  :enddate ")
				.append("  group by dt.departinvoicesid ")
				.append("  ) de, vehicle v, organization sco,Station st,district dt ")
				.append("  where st.id=r.endstationid ")  
				.append("  and st.districtid=dt.id ")
				.append("  and dv.scheduleid = s.id and s.orgid = sco.id and ")
				.append("  s.islinework = 0 ")
				.append("  and s.routeid = r.id and s.districttype in (0,1,2,3,4) and ")
				.append("  dv.id = de.departinvoicesid(+) ")
				.append("  and dv.scheduleplanid = sp.id and dv.departdate between ")
				.append("  :startdate and ")
				.append("  :enddate ")
				.append("  and sco.id in ")
				.append(orgid)
				.append(" and dv.status <> '1' and dv.vehicleid = ")
				.append("  v.id ")
				.append("  and sp.departdate = dv.departdate group by ")
				.append("  sco.name,r.name,r.id,v.vehicleno,dt.name,st.name ")
				.append("  ) nl on bs.scorgname = nl.scorgname and bs.rname = nl.rname ")
				.append("  and bs.routeid = nl.routeid ")
				.append(" group by bs.rname,bs.name,bs.stationname,bs.scorgname ")
				.append("  ) alls group by name,stationname ")
				.append("  ) dd ")
				.append(" where a.name=b.name and a.stationname=b.stationname ")
				.append(" and dd.name=a.name and dd.stationname=a.stationname")
				.append("  and b.name=c.name(+) and b.stationname=c.stationname(+)")
				.append(" group by rollup(a.name,a.stationname) ")
				.append(" order by a.name,a.stationname ");
		}else{
			sql.append("select decode(grouping(districtname), 1, '', districtname) name,")
			.append(" decode(grouping(endname) + grouping(starttime), 1, '小计', 2, '合计', endname) stationname,")
			.append(" decode(grouping(districtname) + grouping(endname) +")
			.append(" grouping(starttime), 1, '', 2, '', starttime) starttime,")
			.append(" nvl(sum(vehiclenum),0) vehiclenum,")
			.append(" nvl(sum(schedulenum)-sum(overtime), 0) schedulenum,")
			.append(" nvl(sum(ticketnum), 0) ticketnum,")
			.append(" nvl(sum(overtime), 0) overschedulenum,")
			.append(" nvl(sum(schedulenum), 0) allschedulenum,")
			.append(" nvl(sum(overtimeticketnum), 0) overticketnum,")
			.append(" nvl(sum(totalamount), 0) moneypayable,")
			.append(" nvl(sum(peopledistance), 0) peopledistance,")
			.append(" nvl((case sum(needpeopledistance) when 0 then '0'")
			.append(" else (to_char(sum(peopledistance) * 100 / sum(needpeopledistance), '990.99')) end),0) || '%' as rate")
			.append(" from (select ")
			.append(" bs.endname, bs.districtname, bs.vehiclenum, s.starttime,")
			.append(" bs.seats, bs.needschedulenum, bs.needpeopledistance, nl.distance,")
			.append(" nl.schedulenum, nl.overtime, nl.invoicesnonum, nl.ticketnum,")
			.append(" nl.overtimeticketnum, nl.totalamount, nl.peopledistance")
			.append(" from (select  es.name endname, dt.name districtname,")
			.append(" r.id routeid,")
			.append(" count(distinct v.id) vehiclenum,")
			.append(" sc.id scheduleid,")
			.append(" sum(v.seatnum) seats,")
			.append(" count(vp.vehicleid) needschedulenum,")
			.append(" sum(v.seatnum * r.distance) needpeopledistance")
			.append(" from schedulestatus ss,")
			.append(" scheduleplan   sp,")
			.append(" vehiclereport  vp,")
			.append(" vehicle        v,")
			.append(" schedule       sc,")
			.append(" route          r,")
			.append(" organization   sco,")
			.append(" station        es,")
			.append(" district       dt")
			.append(" where ss.scheduleplanid = sp.id")
			.append(" and ss.scheduleid = sc.id")
			.append(" and sc.routeid = r.id")
			.append(" and sc.islinework = 1")
			.append(" and sp.id = vp.scheduleplanid")
			.append(" and vp.isactive = 1")
			.append(" and ss.departstationid = sco.stationid")
			.append(" and vp.vehicleid = v.id")
			.append(" and sc.orgid = sco.id")
			.append(" and ss.departdate = sp.departdate")
			.append(" and r.endstationid=es.id")
			.append(" and dt.id=es.districtid")
			.append(" and sp.departdate between :startdate and  :enddate")
			.append(" and sco.id in "+orgid)
			.append(" group by  es.name, dt.name, r.id, sc.id) bs")
			.append(" left join (select")
			.append(" es.name endname,")
			.append("  dt.name districtname,")
			.append(" r.id routeid,")
			.append(" count(distinct v.id) vehiclenum,")
			.append(" s.id scheduleid,")
			.append(" sum(r.distance) distance,")
			.append(" count(distinct dv.reportid) as schedulenum,")
			.append(" sum(case when s.isovertime = 1 then")
			.append(" 1 else 0  end) overtime,")
			.append(" count(distinct dv.departinvoicesno) as invoicesnonum,")
			.append(" sum(case when s.isovertime=0 then dv.ticketnum else 0 end) as ticketnum,")
			.append(" sum(case when s.isovertime=1 then dv.ticketnum else 0 end) as overtimeticketnum,")
			.append(" sum(dv.totalamount) as totalamount,")
			.append(" sum(dv.stationservicefee + dv.othterfee +")
			.append(" dv.agentfee) income,")
			.append(" sum(dv.balanceamount) balanceamount,")
			.append(" sum(de.peopledistance) peopledistance,")
			.append(" sum(dv.moreprice) moreprice")
			.append(" from departinvoices dv,")
			.append(" route r,")
			.append(" schedule s,")
			.append(" district dt,")
			.append(" scheduleplan sp,")
			.append(" (select dt.departinvoicesid,")
			.append(" sum(dt.distance * dt.ticketnum) peopledistance")
			.append(" from departinvoicesdetail dt")
			.append(" where dt.departdate between :startdate  and :enddate")
			.append(" group by dt.departinvoicesid) de,")
			.append(" vehicle v,")
			.append(" station es,")
			.append(" organization sco")
			.append(" where dv.scheduleid = s.id")
			.append(" and s.orgid = sco.id")
			.append(" and s.islinework = 1")
			.append(" and s.routeid = r.id")
			.append(" and dv.id = de.departinvoicesid(+)")
			.append(" and dv.scheduleplanid = sp.id")
			.append(" and dv.departdate between :startdate and  :enddate")
			.append(" and sco.id in "+orgid)
			.append(" and dv.status <> '1'")
			.append(" and dv.vehicleid = v.id")
			.append(" and r.endstationid= es.id")
			.append(" and dt.id=es.districtid")
			.append(" and sp.departdate = dv.departdate")
			.append(" group by es.name, dt.name,r.id, s.id) nl ")
			.append(" on bs.endname= nl.endname")
			.append(" and bs.districtname=nl.districtname")
			.append(" and bs.routeid = nl.routeid")
			.append(" and bs.scheduleid = nl.scheduleid,")
			.append(" route r, schedule s")
			.append(" where r.id = s.routeid")
			.append(" and r.id = bs.routeid")
			.append(" and bs.scheduleid = s.id")
			.append(" union all")
			.append(" select")
			.append(" bs.endname,")
			.append(" bs.districtname,")
			.append(" nl.vehiclenum,")
			.append(" s.starttime,")
			.append(" bs.seats,")
			.append(" bs.needschedulenum,")
			.append(" bs.needpeopledistance,")
			.append(" nl.distance,")
			.append(" nl.schedulenum,")
			.append(" nl.overtime,")
			.append(" nl.invoicesnonum,")
			.append(" nl.ticketnum,")
			.append(" nl.overtimeticketnum,")
			.append(" nl.totalamount,")
			.append(" nl.peopledistance")
			.append(" from (select")
			.append(" es.name endname,")
			.append(" dt.name districtname,")
			.append(" r.id routeid,")
			.append(" sc.id scheduleid,")
			.append(" sum(sp.seatnum - sp.fixedreserveseatnum) seats,")
			.append(" count(sp.id) needschedulenum,")
			.append(" sum((sp.seatnum - sp.fixedreserveseatnum) * r.distance) needpeopledistance")
			.append(" from schedulestatus ss,")
			.append(" scheduleplan   sp,")
			.append(" schedule       sc,")
			.append(" route          r,")
			.append(" organization   sco,")
			.append(" vehiclereport  rp,")
			.append(" vehicle        v,")
			.append(" station        es,")
			.append(" district       dt")
			.append(" where ss.scheduleplanid = sp.id")
			.append(" and ss.scheduleid = sc.id")
			.append(" and sc.routeid = r.id")
			.append(" and sc.islinework = 0")
			.append(" and sc.orgid = sco.id")
			.append(" and ss.departdate = sp.departdate")
			.append(" and sp.departdate between :startdate and  :enddate")
			.append(" and sco.id in "+orgid)
			.append(" and rp.scheduleplanid = sp.id")
			.append(" and sc.id = rp.scheduleid")
			.append("  and rp.vehicleid = v.id")
			.append(" and rp.isactive = 1")
			.append(" and r.endstationid=es.id")
			.append(" and es.districtid= dt.id")
			.append(" group by es.name,dt.name, r.id, sc.id) bs")
			.append(" left join (select ")
			.append(" es.name endname,")
			.append(" dt.name districtname,")
			.append(" r.id routeid,")
			.append(" count(distinct v.id) vehiclenum,")
			.append(" s.id scheduleid,")
			.append(" sum(r.distance) distance,")
			.append(" count(distinct dv.reportid) as schedulenum,")
			.append(" count(distinct case when s.isovertime = 1 then")
			.append(" dv.reportid end) overtime,")
			.append(" count(distinct dv.departinvoicesno) as invoicesnonum,")
			.append(" sum(case when s.isovertime=0 then dv.ticketnum else 0 end) as ticketnum,")
			.append(" sum(case when s.isovertime=1 then dv.ticketnum else 0 end) as overtimeticketnum,")
			.append(" sum(dv.totalamount) as totalamount,")
			.append(" sum(dv.stationservicefee + dv.othterfee + dv.agentfee) income,")
			.append(" sum(dv.balanceamount) balanceamount,")
			.append(" sum(de.peopledistance) peopledistance,")
			.append(" sum(dv.moreprice) moreprice")
			.append(" from departinvoices dv,")
			.append("  route r,")
			.append(" schedule s,")
			.append(" scheduleplan sp,")
			.append(" (select dt.departinvoicesid,")
			.append(" sum(dt.distance * dt.ticketnum) peopledistance")
			.append(" from departinvoicesdetail dt")
			.append(" where dt.departdate between :startdate  and :enddate")
			.append(" group by dt.departinvoicesid) de,")
			.append(" vehicle v,")
			.append(" station es,")
			.append(" district dt,")
			.append(" organization sco")
			.append(" where dv.scheduleid = s.id")
			.append(" and s.orgid = sco.id")
			.append(" and s.islinework = 0")
			.append(" and s.routeid = r.id")
			.append(" and dv.id = de.departinvoicesid(+)")
			.append(" and dv.scheduleplanid = sp.id")
			.append(" and dv.departdate between :startdate and  :enddate")
			.append(" and sco.id in "+orgid)
			.append(" and dv.status <> '1'")
			.append(" and dv.vehicleid = v.id")
			.append(" and r.endstationid=es.id")
			.append(" and dt.id=es.districtid")
			.append(" and sp.departdate = dv.departdate")
			.append(" group by es.name,dt.name, r.id, s.id) nl ")
			.append(" on bs.endname = nl.endname")
			.append(" and bs.districtname= nl.districtname")
			.append(" and bs.routeid = nl.routeid")
			.append(" and bs.scheduleid = nl.scheduleid,")
			.append(" route r, schedule s")
			.append(" where r.id = s.routeid")
			.append(" and r.id = bs.routeid")
			.append(" and bs.scheduleid = s.id) alls")
			.append(" group by rollup(districtname,endname, starttime) ");
		}
		Query query = getEntityManager().createNativeQuery(sql.toString());
		query.setParameter("startdate", startdate);
		query.setParameter("enddate", enddate);
		return query.getResultList();
	}
}
